Refactor project and add basic shell completion
WolvenKit/gpm pull request #19
Opened 2021-01-06 15:14 UTC by cfi2017

I've gone through the points I made on discord a couple days ago and implemented the most glaring changes:
- you don't (read shouldn't) have a go.mod file in every one of your subdirectories  
=> I've reduced the entire structure down to a single go.mod file in the root directory to simplify dependency management.
- I'd rename all your main.go files to something more descriptive (eg config.go for configuration) as main usually denotes an entrypoint  
=> I've removed one redundant (empty) main.go file and refactored the others to match their respective package name.
- I'd move your structures to a model package or something similar in either the internal package or, better, the pkg package. That allows people to easily find models (atm the mod struct is defined in mod/main.go, the registry struct in game/mod_registry.go, moving it makes it clearer)  
=> I have not yet looked at this, due to complexity of the refactor and the models being a little more complex than I initially thought.
- I'd keep my tests close to the actual code files they test. You can keep helpers in the test files, they won't be compiled with the application. _test.go denotes a test file, this is treated differently by the compiler (so for example download might have a download_test file in the same directory). the test directory on the root folder is by definition more for loosely coupled test related data like third party test tools, test data and such, not necessarily for unit tests  
=> Tests are still the same, I have also not looked at test content yet
- I'd consider moving everything in your ./cmd folder into a ./internal/commands folder and then moving your root main.go file to ./cmd/gpm/main.go. This allows you to then run go build ./cmd/gpm to build the application and clearly denotes the entrypoint while also adding support for multiple entrypoints.  
=> Done, `go build ./cmd/gpm` should now result in the wanted binary.
- For releases, I find goreleaser pairs really well with github actions (see an example of it here: https://github.com/cfi2017/bl3-save). It allows you to build for a os/arch matrix so you can do multi-platform builds and automatically propagates changelogs for you (important files in the above repo are .goreleaser.yml and the github actions configuration)  
=> Goreleaser is now added, I have not however done a tagged commit to test this part of the CI.

2021-01-06 19:02 UTC, osulli requested changes
That's great. Thanks for the refactor and gorelease + linter recommendations.

As discussed, please can you add the linter to the pre-commit config file + update Makefile where appropriate.

Thanks

2021-01-06 19:02 UTC, osulli commented on .github/workflows/analysis.yaml
> +      - "v*"
Can you change this to just wildcard please?

I prefer versioning as "x.x.x" not "vx.x.x" as it is redundant when discussing versions.

2021-01-06 19:02 UTC, osulli commented on .github/workflows/release.yaml
> +      - 'v*.*.*'
Same again here please with the v

We'll version both the release and tag itself with semver

2021-01-06 19:02 UTC, osulli commented on .github/workflows/release.yaml
> +          go-version: 1.14.x
Will this be ok with the hardcoded `.x`

2021-01-06 19:02 UTC, osulli commented on .goreleaser.yml
> +          - 386
What is 386?

2021-01-06 19:10 UTC, osulli requested changes
Also, is there a reason `go test ...` or `make test` is no longer running on PRs?

2021-01-06 21:00 UTC, cfi2017 commented on .goreleaser.yml
> +          - 386
32 bit compilation, just adds to the matrix. adds a couple more build strategies

2021-01-06 21:03 UTC, cfi2017 commented on .github/workflows/release.yaml
> +          go-version: 1.14.x
Changing this to v1.15, though 1.14.x should have been fine

2021-01-06 21:03 UTC, cfi2017 commented
> Also, is there a reason `go test ...` or `make test` is no longer running on PRs?

I left that out for now until we have a more stabilised test structure. I'd like to re-add that as a step after the linting process but I haven't gotten to it yet

2021-01-08 13:21 UTC, MythicManiac commented
You might want to direct this PR to https://github.com/WolvenKit/gpm-go now that the repos are separated

2021-01-08 23:50 UTC, osulli commented
https://github.com/WolvenKit/gpm-go/pull/1 merged

2021-01-08 23:50 UTC, closed without merging